# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: API Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

jobs:
  todo:
    defaults:
      run:
        working-directory: ./api
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm test
      - run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report --partial -l TypeScript -r ./coverage/lcov.info
      - run: npm run build
  user:
    needs: [todo]
    defaults:
      run:
        working-directory: ./user
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm test
      - run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report --partial -l TypeScript -r ./coverage/lcov.info
      - run: npm run build
  infra:
    needs: [todo, user]
    defaults:
      run:
        working-directory: ./infrastructure
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: npm test
      - run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report --partial -l TypeScript -r ./coverage/lcov.info
      - run: bash <(curl -Ls https://coverage.codacy.com/get.sh) final